package com.google.android.gms.fido;

import com.google.android.gms.common.Feature;

/* compiled from: com.google.android.gms:play-services-fido@@20.1.0 */
public final class zza {
    public static final Feature zza;
    public static final Feature zzb;
    public static final Feature zzc;
    public static final Feature zzd;
    public static final Feature zze;
    public static final Feature zzf;
    public static final Feature zzg;
    public static final Feature zzh;
    public static final Feature zzi;
    public static final Feature zzj;
    public static final Feature zzk;
    public static final Feature zzl;
    public static final Feature zzm;
    public static final Feature zzn;
    public static final Feature zzo;
    public static final Feature zzp;
    public static final Feature zzq;
    public static final Feature zzr;
    public static final Feature zzs;
    public static final Feature zzt;
    public static final Feature zzu;
    public static final Feature zzv;
    public static final Feature zzw;
    public static final Feature zzx;
    public static final Feature zzy;
    public static final Feature[] zzz;

    static {
        Feature feature = new Feature("cancel_target_direct_transfer", 1);
        zza = feature;
        Feature feature2 = new Feature("delete_credential", 1);
        zzb = feature2;
        Feature feature3 = new Feature("delete_device_public_key", 1);
        zzc = feature3;
        Feature feature4 = new Feature("get_or_generate_device_public_key", 1);
        zzd = feature4;
        Feature feature5 = new Feature("get_passkeys", 1);
        zze = feature5;
        Feature feature6 = new Feature("update_passkey", 1);
        zzf = feature6;
        Feature feature7 = new Feature("is_user_verifying_platform_authenticator_available_for_credential", 1);
        zzg = feature7;
        Feature feature8 = new Feature("is_user_verifying_platform_authenticator_available", 1);
        zzh = feature8;
        Feature feature9 = new Feature("privileged_api_list_credentials", 2);
        zzi = feature9;
        Feature feature10 = new Feature("start_target_direct_transfer", 1);
        zzj = feature10;
        Feature feature11 = new Feature("first_party_api_get_link_info", 1);
        zzk = feature11;
        Feature feature12 = new Feature("zero_party_api_register", 3);
        zzl = feature12;
        Feature feature13 = new Feature("zero_party_api_sign", 3);
        zzm = feature13;
        Feature feature14 = new Feature("zero_party_api_list_discoverable_credentials", 2);
        zzn = feature14;
        Feature feature15 = new Feature("zero_party_api_authenticate_passkey", 1);
        zzo = feature15;
        Feature feature16 = feature15;
        Feature feature17 = new Feature("zero_party_api_register_passkey", 1);
        zzp = feature17;
        Feature feature18 = feature17;
        Feature feature19 = new Feature("zero_party_api_register_passkey_with_sync_account", 1);
        zzq = feature19;
        Feature feature20 = feature19;
        Feature feature21 = new Feature("zero_party_api_get_hybrid_client_registration_pending_intent", 1);
        zzr = feature21;
        Feature feature22 = feature21;
        Feature feature23 = new Feature("zero_party_api_get_hybrid_client_sign_pending_intent", 1);
        zzs = feature23;
        Feature feature24 = feature23;
        Feature feature25 = new Feature("get_browser_hybrid_client_sign_pending_intent", 1);
        zzt = feature25;
        Feature feature26 = feature25;
        Feature feature27 = new Feature("get_browser_hybrid_client_registration_pending_intent", 1);
        zzu = feature27;
        Feature feature28 = feature27;
        Feature feature29 = new Feature("privileged_authenticate_passkey", 1);
        zzv = feature29;
        Feature feature30 = feature29;
        Feature feature31 = new Feature("privileged_register_passkey_with_sync_account", 1);
        zzw = feature31;
        Feature feature32 = feature31;
        Feature feature33 = new Feature("zero_party_api_get_privileged_hybrid_client_registration_pending_intent", 1);
        zzx = feature33;
        Feature feature34 = new Feature("zero_party_api_get_privileged_hybrid_client_sign_pending_intent", 1);
        zzy = feature34;
        zzz = new Feature[]{feature, feature2, feature3, feature4, feature5, feature6, feature7, feature8, feature9, feature10, feature11, feature12, feature13, feature14, feature16, feature18, feature20, feature22, feature24, feature26, feature28, feature30, feature32, feature33, feature34};
    }
}
