package com.google.android.gms.internal.pal;

import java.net.InetAddress;
import java.net.URI;
import java.net.URL;
import java.util.BitSet;
import java.util.Calendar;
import java.util.Currency;
import java.util.GregorianCalendar;
import java.util.Locale;
import java.util.UUID;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.concurrent.atomic.AtomicIntegerArray;

/* compiled from: com.google.android.gms:play-services-pal@@20.0.1 */
public final class zzaba {
    public static final zzzg zzA = new zzaaa();
    public static final zzzg zzB = new zzaab();
    public static final zzzh zzC;
    public static final zzzg zzD;
    public static final zzzh zzE;
    public static final zzzg zzF;
    public static final zzzh zzG;
    public static final zzzg zzH;
    public static final zzzh zzI;
    public static final zzzg zzJ;
    public static final zzzh zzK;
    public static final zzzg zzL;
    public static final zzzh zzM;
    public static final zzzg zzN;
    public static final zzzh zzO;
    public static final zzzg zzP;
    public static final zzzh zzQ;
    public static final zzzg zzR;
    public static final zzzh zzS;
    public static final zzzg zzT;
    public static final zzzh zzU;
    public static final zzzg zzV;
    public static final zzzh zzW;
    public static final zzzh zzX = new zzaan();
    public static final zzzg zza;
    public static final zzzh zzb;
    public static final zzzg zzc;
    public static final zzzh zzd;
    public static final zzzg zze;
    public static final zzzg zzf = new zzaau();
    public static final zzzh zzg;
    public static final zzzg zzh;
    public static final zzzh zzi;
    public static final zzzg zzj;
    public static final zzzh zzk;
    public static final zzzg zzl;
    public static final zzzh zzm;
    public static final zzzg zzn;
    public static final zzzh zzo;
    public static final zzzg zzp;
    public static final zzzh zzq;
    public static final zzzg zzr;
    public static final zzzh zzs;
    public static final zzzg zzt = new zzzu();
    public static final zzzg zzu = new zzzv();
    public static final zzzg zzv = new zzzw();
    public static final zzzg zzw;
    public static final zzzh zzx;
    public static final zzzg zzy;
    public static final zzzg zzz = new zzzz();

    static {
        zzzg zzc2 = new zzaad().zzc();
        zza = zzc2;
        zzb = new zzaap(Class.class, zzc2);
        zzzg zzc3 = new zzaao().zzc();
        zzc = zzc3;
        zzd = new zzaap(BitSet.class, zzc3);
        zzaat zzaat = new zzaat();
        zze = zzaat;
        zzg = new zzaaq(Boolean.TYPE, Boolean.class, zzaat);
        zzaav zzaav = new zzaav();
        zzh = zzaav;
        zzi = new zzaaq(Byte.TYPE, Byte.class, zzaav);
        zzaaw zzaaw = new zzaaw();
        zzj = zzaaw;
        zzk = new zzaaq(Short.TYPE, Short.class, zzaaw);
        zzaax zzaax = new zzaax();
        zzl = zzaax;
        zzm = new zzaaq(Integer.TYPE, Integer.class, zzaax);
        zzzg zzc4 = new zzaay().zzc();
        zzn = zzc4;
        zzo = new zzaap(AtomicInteger.class, zzc4);
        zzzg zzc5 = new zzaaz().zzc();
        zzp = zzc5;
        zzq = new zzaap(AtomicBoolean.class, zzc5);
        zzzg zzc6 = new zzzt().zzc();
        zzr = zzc6;
        zzs = new zzaap(AtomicIntegerArray.class, zzc6);
        zzzx zzzx = new zzzx();
        zzw = zzzx;
        zzx = new zzaaq(Character.TYPE, Character.class, zzzx);
        zzzy zzzy = new zzzy();
        zzy = zzzy;
        zzC = new zzaap(String.class, zzzy);
        zzaac zzaac = new zzaac();
        zzD = zzaac;
        zzE = new zzaap(StringBuilder.class, zzaac);
        zzaae zzaae = new zzaae();
        zzF = zzaae;
        zzG = new zzaap(StringBuffer.class, zzaae);
        zzaaf zzaaf = new zzaaf();
        zzH = zzaaf;
        zzI = new zzaap(URL.class, zzaaf);
        zzaag zzaag = new zzaag();
        zzJ = zzaag;
        zzK = new zzaap(URI.class, zzaag);
        zzaah zzaah = new zzaah();
        zzL = zzaah;
        zzM = new zzaas(InetAddress.class, zzaah);
        zzaai zzaai = new zzaai();
        zzN = zzaai;
        zzO = new zzaap(UUID.class, zzaai);
        zzzg zzc7 = new zzaaj().zzc();
        zzP = zzc7;
        zzQ = new zzaap(Currency.class, zzc7);
        zzaak zzaak = new zzaak();
        zzR = zzaak;
        zzS = new zzaar(Calendar.class, GregorianCalendar.class, zzaak);
        zzaal zzaal = new zzaal();
        zzT = zzaal;
        zzU = new zzaap(Locale.class, zzaal);
        zzaam zzaam = new zzaam();
        zzV = zzaam;
        zzW = new zzaas(zzyy.class, zzaam);
    }
}
